#!/usr/bin/env node
// create-sheet.mjs
// Creates a "CallBuddy Latency" Google Sheet using the service account key,
// shares it with the user's personal Google account, and writes GOOGLE_SHEET_ID to .env.
//
// Usage: node scripts/create-sheet.mjs <user-email>
// Called automatically by setup-google.ps1.

import { google } from "googleapis";
import { readFileSync, writeFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT      = resolve(__dirname, "..");

// ── Args ─────────────────────────────────────────────────────────────────────

const userEmail = process.argv[2] ?? "yuvrajs.batra@gmail.com";

// ── Load credentials ──────────────────────────────────────────────────────────

const credsPath = resolve(ROOT, "google-credentials.json");
if (!existsSync(credsPath)) {
  console.error("[create-sheet] google-credentials.json not found at", credsPath);
  process.exit(1);
}

const credentials = JSON.parse(readFileSync(credsPath, "utf-8"));

// ── Auth clients ──────────────────────────────────────────────────────────────

const sheetsAuth = new google.auth.GoogleAuth({
  credentials,
  scopes: [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
  ],
});

const sheets = google.sheets({ version: "v4", auth: sheetsAuth });
const drive  = google.drive({ version: "v3", auth: sheetsAuth });

// ── Create spreadsheet ────────────────────────────────────────────────────────

console.log("[create-sheet] Creating spreadsheet 'CallBuddy Latency'...");

const createRes = await sheets.spreadsheets.create({
  requestBody: {
    properties: { title: "CallBuddy Latency" },
    sheets: [{
      properties: {
        title: "Latency",
        gridProperties: { frozenRowCount: 1 },
      },
    }],
  },
});

const spreadsheetId  = createRes.data.spreadsheetId;
const spreadsheetUrl = createRes.data.spreadsheetUrl;

console.log("[create-sheet] Created:", spreadsheetUrl);

// ── Write header row ──────────────────────────────────────────────────────────

const HEADERS = [
  "Timestamp",
  "Call SID",
  "User Text",
  "LLM Model",
  "ms Speech→First Token",
  "ms Speech→Last Token",
  "ms Total Response",
  "Interrupted",
];

await sheets.spreadsheets.values.update({
  spreadsheetId,
  range: "Latency!A1",
  valueInputOption: "USER_ENTERED",
  requestBody: { values: [HEADERS] },
});

// Bold + freeze the header row via batchUpdate
await sheets.spreadsheets.batchUpdate({
  spreadsheetId,
  requestBody: {
    requests: [{
      repeatCell: {
        range: { sheetId: 0, startRowIndex: 0, endRowIndex: 1 },
        cell: { userEnteredFormat: { textFormat: { bold: true } } },
        fields: "userEnteredFormat.textFormat.bold",
      },
    }],
  },
});

console.log("[create-sheet] Header row written and formatted.");

// ── Share with user ───────────────────────────────────────────────────────────

console.log(`[create-sheet] Sharing with ${userEmail} (editor)...`);

await drive.permissions.create({
  fileId: spreadsheetId,
  requestBody: {
    type: "user",
    role: "writer",
    emailAddress: userEmail,
  },
  sendNotificationEmail: false,
});

console.log("[create-sheet] Shared.");

// ── Update .env ───────────────────────────────────────────────────────────────

const envPath = resolve(ROOT, ".env");

let envContent = existsSync(envPath) ? readFileSync(envPath, "utf-8") : "";

// Replace existing GOOGLE_SHEET_ID line or append it
if (/^GOOGLE_SHEET_ID=.*/m.test(envContent)) {
  envContent = envContent.replace(
    /^GOOGLE_SHEET_ID=.*/m,
    `GOOGLE_SHEET_ID=${spreadsheetId}`
  );
  console.log("[create-sheet] Updated GOOGLE_SHEET_ID in .env");
} else {
  // Append after a blank line
  if (!envContent.endsWith("\n")) envContent += "\n";
  envContent += `\n# Google Sheets (auto-generated by setup-google.ps1)\nGOOGLE_SHEET_ID=${spreadsheetId}\n`;
  console.log("[create-sheet] Appended GOOGLE_SHEET_ID to .env");
}

writeFileSync(envPath, envContent, "utf-8");

// ── Done ──────────────────────────────────────────────────────────────────────

console.log("");
console.log("✓ Google Sheet ready");
console.log("  ID  :", spreadsheetId);
console.log("  URL :", spreadsheetUrl);
console.log("  .env: GOOGLE_SHEET_ID written");
console.log("");
console.log("Open the sheet:");
console.log(" ", spreadsheetUrl);
