name: CallBuddy Night Idle
on:
  schedule:
    - cron: '0 11 * * *'
    - cron: '0 17 * * *'
jobs:
  stop:
    if: github.event.schedule == '0 11 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with: { creds: '${{ secrets.AZURE_CREDENTIALS }}' }
      - run: az webapp stop --name callbuddy-app --resource-group batra-rg
  start:
    if: github.event.schedule == '0 17 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with: { creds: '${{ secrets.AZURE_CREDENTIALS }}' }
      - run: az webapp start --name callbuddy-app --resource-group batra-rg
